name: money_field
description: A simple to use TextEditingController for handling money values.
version: 1.0.1
author: Eric Grandt <contact@ericgrandt.com>
homepage: https://github.com/Erigitic/money-field

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
